var BaseDatos = new Array(
"/ayuda;Ayuda de El Código;Información sobre cómo utilizar los contenidos de El Código y sobre como navegar por nuestras páginas;ayuda,help",
"/no;Emilio Mendiola Hinojosa;Seg. Publica: Juez Calificador, Sueldo $2,300.00;autores,creditos",
"/no;Nicolas Ortiz Martinez;Seg. Publica: Director, Sueldo $5,000.00",
"/no;Guerrero Rodriguez Juan ;Seg. Publica: Agente, Sueldo $1,173.60",
"/no;Villarreal V. Jose Guadalupe ;Seg. Publica: Sub-Director, Sueldo $ 2,751.15",
"/no;Leon Marquez Jorge ;Seg. Publica: Oficial Patrullero, Sueldo $ 1,173.60 ",
"/no;Muñoz Robledo Ramon ;Seg. Publica: Agente, Sueldo $ 1,173.60 ",
"/no;Leon Marquez Sergio;Seg. Publica: Agente, Sueldo $ 1,173.60 ",
"/no;Rodriguez Jasso Jorge;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Torres Conde Isabel Cristina;Seg. Publica: Secretaria, Sueldo $ 963.00",
"/no;Garcia Flores Tomas;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Medina Lopez Rodolfo;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Ortiz Martinez Maria Esthela;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Ramirez Cortes Martin;Seg. Publica: ninguno, Sueldo $ 963.00",
"/no;Diaz Luna Angel;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Ramirez Lopez Carlos;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Rodriguez Jasso Victor;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Carrillo Olvera Jorge;Seg. Publica: Agente, Sueldo $ 1,173.60",
"/no;Martinez Garza Victor Manuel;Seg. Publica: Agente, Sueldo $ 1,924.20",
"/no;Hernandez Acuña Adrian;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Castillo Castillo Margarita;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Alcala Yañez Hector Javier;Seg. Publica: Agente, Sueldo $ 1,173.60 ",
"/no;Barrientos Vazquez Mario;Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Alfaro Peñaflor Jesus; Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Hernandez Collazo Jorge H.; Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Gonzalez Gomez Martha Irene.; Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Garcia Rodriguez Pedro.; Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Esparza Perez Luis Miguel.; Seg. Publica: Agente, Sueldo $ 963.00",
"/no;Reynaldo Conde Torres.; Seg. Publica: Policia Aux. Hosp Rural, Sueldo $ 1,173.60",
"/no;Rafael Reyes Camacho.; Seg. Publica: Policia Aux. Hosp Rural, Sueldo $ 1,173.60",
"/no;Rafael Luna Peralta.;  Auxiliar. , Sueldo $ 963.00",
"/no;Cepeda Gomez Osvaldo.; Seg. Publica: Comandante, Sueldo $1,120.65 ",
"/no;Montoya Hernandez Refugio.; Seg. Publica: Perito, Sueldo $ 1,173.60",
"/no;Garcia Garza Apolinar.; Seg. Transito Municipal: Agente, Sueldo $ 1,278.45 ",
"/no;Del Angel Vazquez Alberto.; Transito: Agente, Sueldo $ 963.00",
"/no;Arellano Garcia Francisco.; Transito: Agente, Sueldo $ 963.00",
"/no;Lona Muñiz Victor.; Transito: Agente, Sueldo $ 963.00",
"/no;Vela Arellano Emilio; Transito (subdelegacion La Pesca): Agente, Sueldo $ 1,015.50 ",
"/no;Cortina Villarreal Valentin; Transito (subdelegacion La Pesca): Ayundante, Sueldo $ 1,015.50 ",
"/no;Cepeda Mireles Armando; Transito (subdelegacion La Pesca): Agente, Sueldo $ 1,015.50 ",
"/no;Cepeda Hinojosa Reynaldo; Transito (subdelegacion La Pesca): Oficial Patruyero, Sueldo $ 1,173.60 ",
"/no;Portillo Garcia Juan Guadalupe; Transito (subdelegacion La Pesca): Subdelegado, Sueldo $ 1,015.50 ",
"/no;Ochoa Arellano Hermilo; Transito (subdelegacion La Pesca): subComandante, Sueldo $ 1,015.50 ",
"/no;Eulogio Ochoa Cepeda; Transito (subdelegacion La Pesca): Agente, Sueldo $ 1,015.50 ",
"/no;Cepeda Reyes Saul; Transito (subdelegacion La Pesca): Agente, Sueldo $ 1,015.50 ",
"/no;Ochoa Garcia Alvaro; Transito (subdelegacion La Pesca): Agente, Sueldo $ 1,015.50 ",
"/no;Cepeda Perez Leonardo; Transito (subdelegacion La Pesca): Juez Calificador, Sueldo $ 1,015.50 ",
"/no;Cortina Espino Valentin; Transito (subdelegacion La Pesca): Delegado, Sueldo $1,068.30 ",
"/no;Cepeda Espino Eudelio; Transito (subdelegacion La Pesca): Agente, Sueldo $ 1,015.50 ",
"/no;Bañuelos Aguilar Jorge; Transito (Tampiquito): Delegado, Sueldo $ 963.00 ",
"/no;Leonel Arellano Ochoa.; Presidente Municipal: Soto la Marina, Sueldo $ 17,500.00",
"/no;Yesenia Espino Vela.; Presidencia:Secretaria, Sueldo $ 1,173.60",
"/no;Herminia Hernandez Juarez; Presidencia:Encargada De Aseo, Sueldo $ 1,200.00  ",
"/no;Maribel Meza Esparza; Presidencia:Auxiliar, Sueldo $ 594.60 ",
"/no;Guadalupe Ramirez Mireles; Presidencia:Recepcionista, Sueldo $ 1,708.95  ",
"/no;Mario Ramirez Dominguez; Presidencia:Auxiliar, Sueldo $ 2,100.00  ",
"/no;Gaspar Arellano Galvan; Presidencia:Secretario , Sueldo $ 8,500.00  ",
"/no;Marco Antonio Castro Narvaez; cabildo: 5to Regidor, Sueldo $ 9,800.00  ",
"/no;Claudio Reyna Garcia; cabildo: 1er Regidor, Sueldo $ 9,800.00  ",
"/no;Elizabeth Flores Cardenas; cabildo: 2do Regidor, Sueldo $ 9,800.00  ",
"/no;Ramon Gomez Leal; cabildo: 3er Regidor, Sueldo $ 9,800.00  ",
"/no;Monica Jimentez Gutierrez; cabildo: 4to Regidor, Sueldo $ 9,800.00  ",
"/no;Hector Hernandez Villarreal; cabildo: 6to Regidor, Sueldo $ 9,800.00  ",

"/no;Ricardo Romero Hinojosa; sindicatura: sindico, Sueldo $ 9,800.00  ",
"/no;San Juana Magdaleno Cortina; sindicatura: secretaria, Sueldo $ 1,050.00  ",
"/no;Silverio Fragoso Jimenez; sindicatura: junta de reclutamiento, Sueldo $ 1,050.00  ",

"/no;Miguel Guerrero Hernandez; Catastro: Apoyo Delegado Estatal, Sueldo $ 1,125.00   ",
"/no;Jose Angel Garcia Ramirez; Catastro: Auxiliar, Sueldo $ 900.00  ",

"/no;Pedro Mares Juarez; Tesoreria: Tesorero, Sueldo $ 5,000.00  ",
"/no;Julio Cesar Ortiz Barrietos; Tesoreria: Auxiliar, Sueldo $ 1,800.00  ",
"/no;Yolanda Chavarria Zarazua; Tesoreria: Auxiliar, Sueldo $ 1,800.00  ",
"/no;Elivinio Yañez Yañez; Tesoreria: Ayundante, Sueldo $ 931.20  ",
"/no;Eduardo Arellano Mireles; Tesoreria: Ayundante de PROCAMPO, Sueldo $ 1,500.00  ",
"/no;Mario Galvan Castillo; Tesoreria: Servicio General, Sueldo $ 1,120.65   ",
"/no;Francisco Javier Yañez Yañez; Tesoreria: Auxiliar, Sueldo $ 1,125.00   ",
"/no;Norma Lidia Ochoa Alcala; Tesoreria: Auxiliar, Sueldo $ 1,125.00   ",
"/no;Caludia Vela Hinojosa; Tesoreria: Auxiliar, Sueldo $  1,800.00   ",
"/no;Mario Ramirez Rodriquez; Contraloria: Auxiliar, Sueldo $  4,500.00   ",
"/no;Filomeno Barrientos; Contraloria: Asesor, Sueldo $  2,250.00    ",
"/no;Juan Lopez Alvarez; Contraloria: Asesor, Sueldo $  1,050.00  ",
"/no;Nidia Reyes Castillo; Contraloria: Secretaria, Sueldo $  963.00    ",
"/no;Juan Humberto Herrera Morales; Proteccion Civil: Director, Sueldo $  3,000.00    ",
"/no;Aristeo Bocanegra  Ventura; Proteccion Civil: SubDirector, Sueldo $ 1,120.95  ",
"/no;Juan Estrada Velazquez ; Proteccion Civil: Auxiliar, Sueldo $  1,120.95    ",
"/no;Everardo Velazquez Hernandez; Proteccion Civil: Auxiliar, Sueldo $   1,120.95 ",
"/no;Jasso Rodriguez Miguel Angel; Proteccion Civil: Auxiliar, Sueldo $   1,173.60    ",
"/no;Jasso Rodriguez Miguel Angel; Rastro Municipal: Supervisor, Sueldo $  1,068.30    ",
"/no;Jose Joaquin Gonzalez Garza; Rastro Municipal: Mvz De Rastro, Sueldo $  1,050.00     ",
"/no;Rene Gonzalez Aparicio; Rastro Municipal: Auxiliar, Sueldo $  857.70    ",
"/no;Luis Meza Lopez; Rastro Municipal: Supervisor de Pieles y Ganado, Sueldo $  1,120.95     ",
"/no;Yara Guadalupe Gomez Arellano; DIF: Coordinadora General, Sueldo $  3,500.00     ",
"/no;Diana Yanet Cepeda Espino; DIF: Secretaria, Sueldo $  1,500.00     ",
"/no;Catalina Espinoza Castillo; DIF: Desayunos Escolares, Sueldo $  1,173.60      ",
"/no;Ma Valentina Castro Echeve; DIF: Despensa y Bodega, Sueldo $  931.20       ",
"/no;Yadira Arguello Rodriguez; DIF: Desayunos Escolares, Sueldo $  931.20     ",
"/no;Gabriela Castellanos Espinoza; DIF: Programa Dia, Sueldo $  1,173.60     ",
"/no;Margarita Cortes Ortiz; DIF: Auxiliar del CRE, Sueldo $ 1,173.60     ",
"/no;Guadalupe Gomez Blanco; DIF: Auxiliar del CRE, Sueldo $  1,173.60     ",
"/no;Diana Garcia Infante; DIF: Psicologa, Sueldo $  1,950.00      ",
"/no;Filiberta Estrada Camacho; DIF: Apoyo, Sueldo $ 1,173.60    ",
"/no;Silvia Rivera Galvan; DIF: Apoyo, Sueldo $ 1,173.60    ",
"/no;Eloisa Garcia Alfaro; DIF: Apoyo, Sueldo $ 1,173.60    ",
"/no;Maria Guadalupe Yañez Yañez; DIF: Apoyo, Sueldo $ 1,173.60    ",
"/no;Ma Guadalupe Blanco Oyervides; DIF: Apoyo, Sueldo $ 1,173.60    ",
"/no;Rediver Rodriguez Garcia; DIF: Chofer, Sueldo $ 1,500.00    ",
"/no;Homero Garza Infante; DIF: Eventos Especiales, Sueldo $ 1,500.00    ",
"/no;Elsa Yañez Arellano; DIF: Eventos Especiales, Sueldo $ 1,500.00    ",
"/no;Jorge Luis Arellano Montelongo; DIF: Abogado, Sueldo $ 1,323.00    ",
"/no;Graciela Perales Alvarez; DIF: Eventos Especiales, Sueldo $ 1,500.00    ",
"/no;Homero Cordova Cortina; DIF: Chofer, Sueldo $ 1,278.00    ",
"/no;Martina Vela Arellano; DIF (La Pesca) : Coordinador, Sueldo $ 3,000.00     ",
"/no;Yolanda Espino Cepeda; DIF (La Pesca) : Secretaria, Sueldo $  699.45     ",
"/no;Guillermina Rodriquez Mireles; DIF (La Pesca) : Limpieza, Sueldo $ 699.45      ",
"/no;Guadalupe Ochoa Cepeda	; DIF (La Pesca) : Limpieza, Sueldo $ 699.45     ",
"/no;Martina Vela Arellano; DIF (La Pesca) : Archivo, Sueldo $  699.45     ",
"/no;Jaime Cortina Vela; DIF (La Pesca) : SubCoordinador, Sueldo $1,120.95     ",
"/no;Pedro Aspino Cepeda; DIF (La Pesca) : Auxiliar, Sueldo $ 699.45    ",
"/no;Laura Izela Cepeda Cepeda; DIF (La Pesca) : Auxiliar, Sueldo $ 699.45    ",
"/no;Ana Maria Vela Yañez	; DIF (La Pesca) : Ayudante, Sueldo $ 699.45    ",
"/no;Rubia Vela Arellano; DIF (La Pesca) : Auxiliar, Sueldo $ 642.45    ",
"/no;Barberena Rodriguez Rocio; DIF (La Pesca) : Auxiliar, Sueldo $ 699.45    ",
"/no;Adolfo Cepeda Ramirez; Obras Publicas (La Pesca) : Supervisor, Sueldo $ 699.45     ",
"/no;Felipe Portillo Arellano; Obras Publicas (La Pesca) : Ayundante, Sueldo $ 646.80     ",
"/no;Abelardo Cepeda Mireles; Obras Publicas (La Pesca) : Ayundante, Sueldo $ 699.45     ",
"/no;Guadalupe Cepeda Herrera; Obras Publicas (La Pesca) : Ayundante, Sueldo $ 699.45     ",
"/no;Agustin Garcia Vela; Obras Publicas (La Pesca) : Chofer del Presidente, Sueldo $ 1,382.40     ",
"/no;Cepeda Garcia Castulo; Obras Publicas (La Pesca) : Agente, Sueldo $ 699.45     ",
"/no;Antonio Fidalgo Garza; Obras Publicas (La Pesca) : Mantenimiento de Playa, Sueldo $ 963.00     ",
"/no;Ancelmo Cepeda Mireles; Obras Publicas (La Pesca) : Mantenimiento de Playa, Sueldo $ 648.45      ",
"/no;Emma Villarreal Aparicio; Obras Publicas (La Pesca) : Ayundante, Sueldo $ 542.25    ",
"/no;Hinojosa Cortina Ruben; COPLADEM : Director, Sueldo $ 3,004.00     ",
"/no;Homero Romero Arellano; Desarrollo Social : Dir Desarrollo Economico, Sueldo $ 1950.00     ",
"/no;Fidencio Garza Gonzalez; Desarrollo Social : Programa tercera edad, Sueldo $ 1,500.00      ",
"/no;Reyes Gpe Infante De Los Reyes; Desarrollo Social : Enlace Municipal de Oportunidades, Sueldo $ 1,950.00   ",
"/no;Jorge Lopez Castro; Desarrollo Social : Aux Oportunidades Zona Sur, Sueldo $646.80      ",
"/no;Miguel Angel Cepeda Vela; Desarrollo Social :Director, Sueldo $ 1,500.00    ",
"/no;Cruz Gamez Juan	; Desarrollo Social : Ninguno, Sueldo $ 2,250.00     ",
"/no;Virginia De La Rosa Magdaleno; Desarrollo Social : Secretaria, Sueldo $ 962.29    ",
"/no;Suri Saday Perez Cepeda	; Desarrollo Social : Coordinadora General, Sueldo $ 2,700.00 ",
"/no;Francisco Silvia Cisneros; Desarrollo Rural Sustentable: Director, Sueldo $ 3,000.00   ",
"/no;Luis Roberto Rangel Gonzalez; Desarrollo Rural Sustentable: Auxiliar Reconversion Productiva, Sueldo $ 1,500.00 							   ",
"/no;Salomon Jasso Guzman; Desarrollo Rural Sustentable: Auxiliar Alianza Para El Campo, Sueldo $ 1500.00   ",
"/no;Martin Enrique Silva Salais; Desarrollo Rural Sustentable: Auxiliar De Informatica, Sueldo $ 1,125.00   ",
"/no;Infante Ramirez Luis Lauro; Desarrollo Rural Sustentable: Responsable de Programas, Sueldo $ 3,000.00    ",
"/no;Laura Esmeralda Garcia Rodriguez; Desarrollo Rural Sustentable: Auxiliar De Cader, Sueldo $ 669.75   ",
"/no;Renato Juventino Cepeda Cepeda; Obras Publicas: Recursos Humanos, Sueldo $2,100.00    ",
"/no;Leopoldo Cordova Acuña; Obras Publicas: Director, Sueldo $3,000.00    ",
"/no;Saul Rodriguez Rodriguez; Obras Publicas: Rotulista, Sueldo $1,125.00    ",
"/no;Bernardo Tobias Zapata; Obras Publicas: Operador de Maquinas, Sueldo $1,050.00    ",
"/no;Abel Soto Rodriguez; Obras Publicas: Mecanico, Sueldo $ 1,125.00    ",
"/no;Maria Gpe Rodriguez Silva; Obras Publicas: Recursos Humanos, Sueldo $2,100.00    ",
"/no;Renato Juventino Cepeda Cepeda; Obras Publicas: Secretaria, Sueldo $1,239.80   ",
"/no;Sergio Zanella Maldonado ; Obras Publicas: Operador de Camion, Sueldo $1,050.00    ",
"/no;Saldaña Garza Silverio; Obras Publicas: Operador de Maquinas Sueldo $2,170.50    ",
"/no;Lozano Gomez Rafael; Obras Publicas: Electricista Sueldo $1,384.20     ",
"/no;Juan Angel Hernandez Gaona; Obras Publicas: Supervisor  Sueldo $ 1,415.40    ",
"/no;Noe Garza Ramirez; Obras Publicas: Supervisor Sueldo $ 1,415.40  ",
"/no;Rafael Alvarez Valdez; Obras Publicas:Auxiliar Sueldo $963.00     ",
"/no;Delfino Ochoa Vela; Limpieza Publica: Auxiliar Mantenimiento Sueldo $1500.00     ",
"/no;Jose Luis Cordova Garcia; Limpieza Publica: Operador de Contenedores Sueldo $963.00      ",
"/no;Erickson Arguello Romero; Limpieza Publica: Ayundante Sueldo $931.20   ",
"/no;Luis Enrique Yañez Alcala; Limpieza Publica: Ayundante Sueldo $931.20   ",
"/no;Eduardo Villarreal Arguello; Limpieza Publica: Ayundante Sueldo $931.20   ",
"/no;Jorge Luis Cardenas Carmona; Limpieza Publica: Ayundante Sueldo $931.20   ",
"/no;Cirilo Carrizalez Alvarado; Limpieza Publica: Basurero Municipal Sueldo $931.20   ",
"/no;Eugenio Arellano Carrera; Limpieza Publica: Basurero Municipal Sueldo $ 646.80      ",
"/no;Benjamin Gonzalez Ramirez; Limpieza Publica: Ayudante  Sueldo $1,014.45      ",
"/no;Fernando Vela Velez; Mantenimiento De Plazas Y Veladores: Supervisor  Sueldo $1,050.00       ",
"/no;Raul Barrientos Garcia; Mantenimiento De Plazas Y Veladores: Plaza Principal  Sueldo $ 699.45        ",
"/no;Doroteo Arguello Mendez; Mantenimiento De Plazas Y Veladores: Plaza Kiosko  Sueldo $ 699.45       ",
"/no;Paulina Gonzalez Negete; Mantenimiento De Plazas Y Veladores: Plaza Tampiquito  Sueldo $648.45       ",
"/no;Joaquin Hinojosa Arellan; Mantenimiento De Plazas Y Veladores: Velador Yonque  Sueldo $ 1,068.30     ",
"/no;Manuel De Jesus Molina Yuca; Mantenimiento De Plazas Y Veladores: Ayudante  Sueldo $856.20         ",
"/no;Mario Moreno Valdez; Mantenimiento De Edificios: Jefe Mtto Ed Y Eq Computo Sueldo $ 1,500.00         ",
"/no;Lidia Espino Yañez; Mantenimiento De Edificios: Limpieza  Sueldo $ 963.00        ",
"/no;Isidro Montelongo Arismendiz; Mantenimiento De Edificios: Carpintero Sueldo $931.20        ",
"/no;Arnulfo Tovias Romero; Mantenimiento De Edificios: Mtto Edificios Sueldo $1,125.00         ",
"/no;Carmen Torres Ramirez; Mantenimiento De Edificios: Limpieza Juzgado Sueldo: $590.60        ",
"/no;Aureliano Yañez Arellano; Mantenimiento Urbano: Jefe Mtto Urbano Y Serv, Sueldo $1,500.00         ",
"/no;Santos Del Angel Infante Garcia; Mantenimiento Urbano: Auxiliar Mtto Urbano Y Serv,  Sueldo :$1,500.00         ",
"/no;Andres Astello Castillo; Panteon Municipal: Responsable,   Sueldo $1,015.00         ",
"/no;Gregorio Villarreal Garcia; Panteon Municipal: Velador,   Sueldo $748.40         ",
"/no;Garcia Gonzalez Jaime; Pensionado,   Sueldo $590.60          ",
"/no;Bertha Alicia Ramirez Alvarez;Enlace Municipal De Educacion: Director,   Sueldo $ 1,500.00          ",
"/no;Fernando Martinez Pacheco;Enlace Municipal De Educacion: Director,   Sueldo $ 856.05          ",
"/no;Rey David Hernandez Moreno;Enlace Municipal De Educacion: Sub Dir Educacion, Cultura Y Recreacion,   Sueldo $ 856.05           ",
"/no;Sergio Barbosa Garcia;Enlace Municipal De Educacion: Director De Casa De La Cultura ,   Sueldo $ 1,500.00          ",
"/no;Laura Esthela Barrientos Castillo;Enlace Municipal De Educacion: Auxiliar Casa De La Cultura,   Sueldo $1,050.00         ",
"/no;Rosa Elena Lorenzo Cruz ;Enlace Municipal De Educacion: Biblioteca,   Sueldo $  929.68          ",
"/no;Nohelia Ramirez Cortes;Enlace Municipal De Educacion: Biblioteca,   Sueldo $  644.55         ",
"/no;Elizabeth Alvarez Rosales;Enlace Municipal De Educacion: Asistente Jardin Col Nva Rosita	,   Sueldo $ 856.05         ",
"/no;Raquel Zapata Camacho;Enlace Municipal De Educacion: Jardin Lazaro Cardenas,   Sueldo $  669.75         ",
"/no;Waldo Zamora Conde;Enlace Municipal De Educacion: Maestro Danza,   Sueldo $   437.85        ",
"/no;Pablo Cardenas Perales	;Enlace Municipal De Educacion: Maestro Danza,   Sueldo $   331.50        ",
"/no;Ochoa Arellano Martina;Servicios Medicos: Gestora De Servicios Medicos,   Sueldo $   1,500.00        ",
"/no;Juan Alberto Garcia Morales;Eventos Especiales:,   Sueldo $   1,500.00        ",
"/no;Marcela Leiva Castillo ; Eventos Especiales:,   Sueldo $   1,500.00        ",
"/no;Martin Ochoa Arellano;Fomento Deportivo: Director,   Sueldo $   1,500.00        ",
"/no;Efren Aleman Garcia;Fomento Deportivo: SubDirector,   Sueldo $   1,500.00        ",
"/no;Gonzalo Lozano Maravilla;Fomento Deportivo: Auxiliar De Mantenimiento,   Sueldo $    962.20         ",
"/no;Jose Ruiz Jimenez;Fomento Deportivo: Limpieza Gimnasio,   Sueldo $   652.20    ",
"/no;Vianey Hernandez Castillo; Oficialia Mayor: Oficial Mayor,   Sueldo $  3,000.00    ",
"/no;Lidia Gpe Martinez Garcia; Oficialia Mayor: Auxiliar,   Sueldo $  1,172.35     ",
"/no;Sergio Bernardo Rangel Ramirez;Comunicacion Social: Auixiliar de Prensa,   Sueldo $   1,500.00    ",
"/no;Juan Jose Pedraza Perales;Pagina de Internet: WebMaster,       ",
"/no;Sr gilberto riestra Rodríguez ;COMAPA SLM: Gerente General, Sueldo: $   8,500.00,       ",
"/no;Ing. Jose Luis Quezada Mendoza ;COMAPA SLM:  Gerente Administrativo, Sueldo: $   5,256.15,       ",
"/no;Ing. Carlos Garcia Galvan ;COMAPA SLM:  Gerente Administrativo, Sueldo: $   4,500.00,       ",
"/no;C. Ma. Elizabeth Garza De León ;COMAPA SLM: Area De Facturacion , Sueldo: $   2,000.00,       ",
"/no;C. Ma. De  Los Angeles Ramirez Rodríguez ;COMAPA SLM: Contabilidad, Sueldo: $    2,189.77,       ",
"/no;C. Francisca Gpe. Arredondo Miranda;COMAPA SLM:Caja, Sueldo: $    1,500.00,       ",
"/no;C. Aurelio Jimenez Mendez ;COMAPA SLM:Lecturista, Sueldo: $    3,504.68,       ",
"/no;C. Mauricio Mares Juarez;COMAPA SLM: Lecturista, Sueldo: $   1,500.00,       ",
"/no;C. Victor Antonio Casimiro ;COMAPA SLM:  Bombero  , Sueldo: $     1,800.00,       ",
"/no;C. Gaspar Torres Tavares ;COMAPA SLM: Bombero, Sueldo: $    1,500.00,       ",
"/no;C. Jose Gpe. Arrellano Torres,;COMAPA SLM: Bombero, Sueldo: $    1,500.00,       ",
"/no;C. Jose Gpe Villarreal Hinojosa;COMAPA SLM: Bombero, Sueldo: $    2,000.00,       ",
"/no;C. Noe Garza Ramirez ;COMAPA SLM: Bombero, Sueldo: $    1,393.81,       ",
"/no;C. Mauro Ramirez Mireles, ;COMAPA SLM: Bombero, Sueldo: $    1,393.81,       ",
"/no;C. Victor Rivera Hernandez ;COMAPA SLM:  Fontanero      , Sueldo: $    2,000.00,       ",
"/no;C. Victor M. Herberth Fornue;COMAPA SLM:  Fontanero, Sueldo: $    1,800.00,       ",
"/no;C. Jose Luis Olivo Molina ;COMAPA SLM:  Ayudante De Fontanero, Sueldo: $  1,200.00,       ",
"/no;C. Gerardo Garcia Gallardo ;COMAPA SLM:  Ayudante De Fontanero, Sueldo: $  1,200.00,       ",
"/no;C. Elias Medellin Garcia ;COMAPA SLM:  Ayudante De Fontanero, Sueldo: $  1,200.00,       ",
"/no;C. Guillermo Garcia Ornelas ;COMAPA SLM:  Ayudante De Fontanero, Sueldo: $  1,200.00,       ",
"/no;C. Jose Alfredo Garcia Castillo ;COMAPA SLM:  Ayudante De Fontanero, Sueldo: $  1,200.00,       ",
"/no;C. Ezequiel Gracia Garcia;COMAPA SLM:  Ayudante De Fontanero, Sueldo: $  1,200.00,       ",
"/no;C. Jesus Garza Hernandez ;COMAPA SLM:  Almacenista, Sueldo: $   1,500.00,       ",
"/tiralineas/tiralineas3;Tiralíneas: Creación de formularios;Script de creación de código para formularios sencillos de 4 campos;scripts,javascripts,tiralineas,ejemplos,código,programación,formularios,campos,textos,cuadros,radios,botones,submit,reset,enviar"

)
